version: 2.1

# Reusable image / compiler definitions
executors:
  gcc7:
    docker:
      - image: gcc:7
        environment:
          CXX: g++
  clang6:
    docker:
      - image: ubuntu:18.04
        environment:
          CXX: clang++-6.0

# Reusable test commands (and initializer for clang 6)
commands:
  init_clang6:
    steps:
      - run: apt-get update -qq
      - run: apt-get install -y clang build-essential git
  make_checkperf:
    steps:
      - checkout
      - run: make
      - run: make amalgamate
      - run: make test
      - run: make checkperf
  make_test:
    steps:
      - checkout
      - run: make
      - run: make amalgamate
      - run: make test
      - run: make checkperf
  cmake_test:
    steps:
      - run: apt-get update -qq
      - run: apt-get install -y cmake
      - checkout
      - run: cmake $CMAKE_TEST_FLAGS
      - run: make
      - run: make test

jobs:
  gcc-avx-01: { executor: gcc7, steps: [ make_checkperf ] }
  gcc-avx-02: { executor: gcc7, steps: [ make_checkperf ] }
  gcc-avx-03: { executor: gcc7, steps: [ make_checkperf ] }
  gcc-avx-04: { executor: gcc7, steps: [ make_checkperf ] }
  gcc-avx-05: { executor: gcc7, steps: [ make_checkperf ] }
  gcc-avx-06: { executor: gcc7, steps: [ make_checkperf ] }
  gcc-avx-07: { executor: gcc7, steps: [ make_checkperf ] }
  gcc-avx-08: { executor: gcc7, steps: [ make_checkperf ] }
  gcc-avx-09: { executor: gcc7, steps: [ make_checkperf ] }
  gcc-avx-10: { executor: gcc7, steps: [ make_checkperf ] }
  gcc-avx-11: { executor: gcc7, steps: [ make_checkperf ] }
  gcc-avx-12: { executor: gcc7, steps: [ make_checkperf ] }
  gcc-avx-13: { executor: gcc7, steps: [ make_checkperf ] }
  gcc-avx-14: { executor: gcc7, steps: [ make_checkperf ] }
  gcc-avx-15: { executor: gcc7, steps: [ make_checkperf ] }
  gcc-avx-16: { executor: gcc7, steps: [ make_checkperf ] }
  gcc-avx-17: { executor: gcc7, steps: [ make_checkperf ] }
  gcc-avx-18: { executor: gcc7, steps: [ make_checkperf ] }
  gcc-avx-19: { executor: gcc7, steps: [ make_checkperf ] }
  gcc-avx-20: { executor: gcc7, steps: [ make_checkperf ] }

  gcc-sse-01: { executor: gcc7, steps: [ make_checkperf ], environment: { ARCHFLAGS: -march=nehalem } }
  gcc-sse-02: { executor: gcc7, steps: [ make_checkperf ], environment: { ARCHFLAGS: -march=nehalem } }
  gcc-sse-03: { executor: gcc7, steps: [ make_checkperf ], environment: { ARCHFLAGS: -march=nehalem } }
  gcc-sse-04: { executor: gcc7, steps: [ make_checkperf ], environment: { ARCHFLAGS: -march=nehalem } }
  gcc-sse-05: { executor: gcc7, steps: [ make_checkperf ], environment: { ARCHFLAGS: -march=nehalem } }
  gcc-sse-06: { executor: gcc7, steps: [ make_checkperf ], environment: { ARCHFLAGS: -march=nehalem } }
  gcc-sse-07: { executor: gcc7, steps: [ make_checkperf ], environment: { ARCHFLAGS: -march=nehalem } }
  gcc-sse-08: { executor: gcc7, steps: [ make_checkperf ], environment: { ARCHFLAGS: -march=nehalem } }
  gcc-sse-09: { executor: gcc7, steps: [ make_checkperf ], environment: { ARCHFLAGS: -march=nehalem } }
  gcc-sse-10: { executor: gcc7, steps: [ make_checkperf ], environment: { ARCHFLAGS: -march=nehalem } }
  gcc-sse-11: { executor: gcc7, steps: [ make_checkperf ], environment: { ARCHFLAGS: -march=nehalem } }
  gcc-sse-12: { executor: gcc7, steps: [ make_checkperf ], environment: { ARCHFLAGS: -march=nehalem } }
  gcc-sse-13: { executor: gcc7, steps: [ make_checkperf ], environment: { ARCHFLAGS: -march=nehalem } }
  gcc-sse-14: { executor: gcc7, steps: [ make_checkperf ], environment: { ARCHFLAGS: -march=nehalem } }
  gcc-sse-15: { executor: gcc7, steps: [ make_checkperf ], environment: { ARCHFLAGS: -march=nehalem } }
  gcc-sse-16: { executor: gcc7, steps: [ make_checkperf ], environment: { ARCHFLAGS: -march=nehalem } }
  gcc-sse-17: { executor: gcc7, steps: [ make_checkperf ], environment: { ARCHFLAGS: -march=nehalem } }
  gcc-sse-18: { executor: gcc7, steps: [ make_checkperf ], environment: { ARCHFLAGS: -march=nehalem } }
  gcc-sse-19: { executor: gcc7, steps: [ make_checkperf ], environment: { ARCHFLAGS: -march=nehalem } }
  gcc-sse-20: { executor: gcc7, steps: [ make_checkperf ], environment: { ARCHFLAGS: -march=nehalem } }

workflows:
  version: 2.1
  perf:
    jobs:
      - gcc-avx-01
      - gcc-avx-02
      - gcc-avx-03
      - gcc-avx-04
      - gcc-avx-05
      - gcc-avx-06
      - gcc-avx-07
      - gcc-avx-08
      - gcc-avx-09
      - gcc-avx-10
      - gcc-avx-11
      - gcc-avx-12
      - gcc-avx-13
      - gcc-avx-14
      - gcc-avx-15
      - gcc-avx-16
      - gcc-avx-17
      - gcc-avx-18
      - gcc-avx-19
      - gcc-avx-20
      - gcc-sse-01
      - gcc-sse-02
      - gcc-sse-03
      - gcc-sse-04
      - gcc-sse-05
      - gcc-sse-06
      - gcc-sse-07
      - gcc-sse-08
      - gcc-sse-09
      - gcc-sse-10
      - gcc-sse-11
      - gcc-sse-12
      - gcc-sse-13
      - gcc-sse-14
      - gcc-sse-15
      - gcc-sse-16
      - gcc-sse-17
      - gcc-sse-18
      - gcc-sse-19
      - gcc-sse-20
